In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

2024-06-11 10:43:16.316024: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-11 10:43:16.316088: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-11 10:43:16.317611: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
df = pd.read_csv("/kaggle/input/insurance-data/insurance_data (1).csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df.shape

(28, 3)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance,test_size = 0.2, random_state = 2)

In [5]:
len(X_train)

22

### Preprocessing: Scale the data so that both age and affordibility are in same scaling range

In [6]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [7]:
X_train_scaled

age  affordibility
16  0.25              0
6   0.55              0
3   0.52              0
21  0.26              0
26  0.23              1
25  0.54              1
12  0.27              0
4   0.46              1
10  0.18              1
5   0.56              1
20  0.21              1
2   0.47              1
7   0.60              0
24  0.50              1
23  0.45              1
18  0.19              0
11  0.28              1
22  0.40              1
27  0.46              1
13  0.29              0
15  0.55              1
8   0.62              1

### Model Building: First build a model in keras/tensorflow and see what weights and bias values it comes up with. We will than try to reproduce same weights and bias in our plain python implementation of gradient descent. Below is the architecture of our simple neural network



In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 818ms/step - accuracy: 0.5000 - loss: 0.7146
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7142
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7138
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7135
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7131
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7127
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7123
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7119
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7116
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7112
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7108
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy

In [11]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 1.0000 - loss: 0.3153


[0.3152589499950409, 1.0]

In [12]:
X_test_scaled

age  affordibility
1   0.25              0
0   0.22              1
14  0.49              1
9   0.61              1
19  0.18              1
17  0.58              1

In [13]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[0.1628204 ],
       [0.41183817],
       [0.7255056 ],
       [0.8266828 ],
       [0.365132  ],
       [0.8045074 ]], dtype=float32)

### Now get the value of weights and bias from the model

In [16]:
coef,intercept = model.get_weights()
coef, intercept

(array([[4.9196653],
        [1.4286091]], dtype=float32),
 array([-2.8673072], dtype=float32))

### The output means w1=5.060867, w2=1.4086502, bias =-2.9137027

### Instead of model.predict, write our own prediction function that uses w1,w2 and bias

In [17]:
def sigmoid(x):
    import math
    return 1 /(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [18]:
def prediction_function(age,affordability):
    weighted_sum = coef[0]*age + coef[1]*affordability +intercept
    return sigmoid(weighted_sum)

In [19]:
prediction_function(.47,1)

/tmp/ipykernel_123/3032983713.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 /(1+math.exp(-x))


0.7054827391901236

In [20]:
prediction_function(.18,1)

/tmp/ipykernel_123/3032983713.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 /(1+math.exp(-x))


0.3651319740357654

### Now we start implementing gradient descent in plain python. Again the goal is to come up with same w1, w2 and bias that keras model calculated. We want to show how keras/tensorflow would have computed these values internally using gradient descent


In [21]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [22]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

## Time to implement the final Gradient descent function

In [23]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    # w1,w2,bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5 # learning rate
    n = len(age)# or you can use affordability
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [24]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.973391914875179, w2:0.9484790550524685, bias:-0.1133436520447742, loss:0.714610156590683
Epoch:1, w1:0.9526050112606814, w2:0.9061888855737805, bias:-0.21202325373024944, loss:0.6844545754122794
Epoch:2, w1:0.9371389216394038, w2:0.8724863718378795, bias:-0.297354777348674, loss:0.6623114062843333
Epoch:3, w1:0.9263972300850559, w2:0.8464964034855741, bias:-0.3708685783767047, loss:0.6463299135248587
Epoch:4, w1:0.9197530021886515, w2:0.8272363836850969, bias:-0.4341501414207025, loss:0.6349055537023248
Epoch:5, w1:0.9165978234998884, w2:0.8137152861544187, bias:-0.48872346395231225, loss:0.6267483980102483
Epoch:6, w1:0.9163723575035057, w2:0.8049995396683411, bias:-0.535980249721865, loss:0.6208785684684357
Epoch:7, w1:0.9185813941347364, w2:0.8002492021116547, bias:-0.577146673201612, loss:0.6165824439197473
Epoch:8, w1:0.9227979840062284, w2:0.7987322635165253, bias:-0.6132761019356343, loss:0.6133562082414478
Epoch:9, w1:0.9286609028533963, w2:0.7998249643661495, bia

(5.776540098602374, 1.5072936283526548, -3.292466234362901)