In [40]:
import numpy as np

In [41]:
y_predicted = np.array([1,1,0,1])
y_true =  np.array([0.30,0.7,1.0,0.5])

## Implement MAE Using Python

In [42]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [43]:
mae(y_true, y_predicted)

Total error is: 2.5
Mean absolute error is: 0.625


0.625

## Implementing mae using numpy

In [44]:
np.mean(np.abs(y_predicted - y_true))

0.625

## Log 0 is undefined so use a number closer to 1

In [45]:
np.log([0.000000000000000001])

array([-41.44653167])

## Use eplison because log of 0 is undefined

In [46]:
epsilon = 1e-15

In [47]:
y_predicted

array([1, 1, 0, 1])

In [48]:
y_predicted_new =[ max(i,epsilon)for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1]

In [49]:
1-epsilon 

0.999999999999999

In [50]:
y_predicted_new =[ min(i,1-epsilon)for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 0.999999999999999]

In [51]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16])

In [52]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

21.587035095855498

In [53]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
log_loss(y_true, y_predicted)

21.587035095855498